### ISSUE TITLE
Cannot find module 'colormin/lib/stripWhitespace'

### ISSUE THREAD

**Issue by spalger** [ben-eb/postcss-colormin#2]
Looks like https://github.com/ben-eb/colormin/commit/6ff9053cbcb75e0b55d7da7201948ad39c7b266c broke the require statement here: https://github.com/ben-eb/postcss-colormin/blob/master/index.js#L8

**Comment by ben-eb** [comment]
Thanks, will take a look. :+1:

**Comment by spalger** [comment]
Gratzi

**Comment by spalger** [comment]
:dancers:

**Comment by ben-eb** [comment]
Got another issue with node 0.10 but that will be fixed in colormin itself. :smile: 

Released as `1.2.4`.

**Comment by dotcypress** [comment]
:+1:
