### ISSUE TITLE
Converts variables

### ISSUE THREAD

**Issue by lukasoppermann** [ben-eb/postcss-colormin#29]
I think css nanos `colormin` converts the following

```
// Before:
color: var(--grey);

// After:
color: grey;
```

Obviously this is wrong behaviour. It should check if there is a `--` before maybe?

**Comment by ben-eb** [comment]
With the latest version and this test case, I can't reproduce;

```js
var cssnano = require('cssnano');

cssnano().process('h1 { color: --var(grey) }').then(result => {
    console.log(result.css);
});
```

Is it some other plugin in your environment?

**Comment by lukasoppermann** [comment]
Hmm, actually I can not seem to reproduce it now either. Weird, maybe some chrome bug. Sorry.
