### ISSUE TITLE
Cannot find module 'colormin/lib/stripWhitespace'

### ISSUE THREAD

**Issue by nihey** [ben-eb/postcss-colormin#3]
Due to the [recent changes](https://github.com/ben-eb/colormin/commit/6ff9053cbcb75e0b55d7da7201948ad39c7b266c) on colormin [this line](https://github.com/ben-eb/postcss-colormin/blob/master/index.js#L8) broke. Correcting this may be trivial, I'll be submitting a pull request soon.

**Comment by ben-eb** [comment]
Already on it! And this is a duplicate. :smile:

https://github.com/ben-eb/postcss-colormin/issues/2

**Comment by nihey** [comment]
Thanks :)
