### ISSUE TITLE
Cannot find module './lib/colormin'

### ISSUE THREAD

**Issue by tomchentw** [ben-eb/postcss-colormin#7]
It actually breaks the code since I just do a fresh `npm install`. Please modify `package.json` to include `lib` folder as well.

**Comment by ben-eb** [comment]
Apologies for the inconvenience. :smile:

**Comment by tomchentw** [comment]
To remove/add depenencies for any changes like [v2.1.2...v2.1.3](https://github.com/ben-eb/postcss-colormin/compare/v2.1.2...v2.1.3) does, I'd suggest to follow semver and release a minor/major version to prevent unexpected failure.

**Comment by tomchentw** [comment]
Thanks for the fast reply! @ben-eb

**Comment by ben-eb** [comment]
Human error. I always try to follow semver. :smile:
